// AUTO‑GENERATED – DO NOT EDIT
// Generated by scripts/generate-decks.js

const dev = import.meta.env.DEV

export default [
  {
    id: "2026-03-10_elixir-node-impact-dashboards",
    title: "ELIXIR Node Impact Dashboards",
    description: "",
    author: "Manuel Feser",
    date: "2026-03-10",
    url: dev
      ? "http://localhost:3033"
      : "/2026-03-10_elixir-node-impact-dashboards/"
  },
  {
    id: "2025-11-21_denbi-ahm",
    title: "de.NBI All Hands Meeting 2025",
    description: "",
    author: "Manuel Feser",
    date: "2025-11-21",
    url: dev
      ? "http://localhost:3032"
      : "/2025-11-21_denbi-ahm/"
  },
  {
    id: "2025-09-10_grc-ib",
    title: "GRC IB 2025",
    description: "",
    author: "Manuel Feser",
    date: "2025-09-10",
    url: dev
      ? "http://localhost:3031"
      : "/2025-09-10_grc-ib/"
  },
  {
    id: "2025-08-28_cordi",
    title: "CoRDI 2025",
    description: "",
    author: "Manuel Feser",
    date: "2025-08-28",
    url: dev
      ? "http://localhost:3030"
      : "/2025-08-28_cordi/"
  }
]
